version: '3'
services:
  db:
    build:
        context: ./
        dockerfile: ./docker/postgress/Dockerfile
    ports:
      - ${HOST_IP}:${POSTGRESS_HOST_PORT}:5432
    volumes:
      - email_pgsql:/var/lib/postgresql/data
    environment:
      ssl: 0
      POSTGRES_USER: ${POSTGRESS_USER}
      POSTGRES_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRES_DB: ${POSTGRESS_DB}
    restart: always

  opendkim:
    build:
        context: ./
        dockerfile: ./docker/opendkim/Dockerfile
    image: opendkim
    restart: always
    volumes:
      - postfix_socket:/var/spool/postfix/private/
      - vmail:/var/vmail/
      - /opt/log/opendkim:/var/log/

  smtp.fivestar.et:
    depends_on:
      - db
      - opendkim
    build:
        context: ./
        dockerfile: ./docker/postfix/Dockerfile
    image: smtp
    restart: always
    ports:
      - ${HOST_IP}:25:25
      - ${HOST_IP}:465:465
      - ${HOST_IP}:587:587
      - ${HOST_IP}:2525:587

    volumes:
      - postfix_socket:/var/spool/postfix/private/
      - vmail:/var/vmail/
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRESS_DB}
      - DB_USER=${POSTGRESS_USER}
      - DB_PASSWORD=${POSTGRESS_PASSWORD}

  ps-admin:
    depends_on:
      - smtp.fivestar.et
    build:
        context: ./
        dockerfile: ./docker/postfix-admin/Dockerfile
    image: "postfix-admin"
    restart: always
    environment:

      POSTFIXADMIN_DB_TYPE: pgsql
      POSTFIXADMIN_DB_HOST: db

      POSTFIXADMIN_DB_USER: ${POSTGRESS_USER}
      POSTFIXADMIN_DB_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTFIXADMIN_DB_NAME: ${POSTGRESS_DB}

      # 
      POSTFIXADMIN_ENCRYPT: dovecot:ARGON2I
      POSTFIXADMIN_DOVECOTPW: /usr/bin/dovecot/ pw -r 5 # Shared volume
      
      # SMTP
      POSTFIXADMIN_SMTP_SERVER: smtp.fivestar.et
      POSTFIXADMIN_SMTP_PORT: 25

      # SETUP Password
      POSTFIXADMIN_SETUP_PASSWORD: ${POSTFIXADMIN_SETUP_PASSWORD}

    ports:
      - ${HOST_IP}:${POSTFIXADMIN_PORT}:80
      - ${HOST_IP}:${POSTFIXADMIN_PORT_TLS}:443
    volumes:
      - postfix-admin_templates:/var/www/html/templates_c
      - /var/www/html/
      - etc-dovecot:/etc/dovecot/:ro

  imap.fivestar.et:
    image: dovecot
    depends_on:
      - smtp.fivestar.et
    build:
      context: ./
      dockerfile: ./docker/dovecot/Dockerfile
    ports:
      - ${HOST_IP}:143:143
      - ${HOST_IP}:993:993    
    restart: always
    volumes:
      - postfix_socket:/var/spool/postfix/private/
      - etc-dovecot:/etc/dovecot/:rw
      - vmail:/var/vmail/
    environment:
      - DB_HOST=db
      - DB_NAME=${POSTGRESS_DB}
      - DB_USER=${POSTGRESS_USER}
      - DB_PASSWORD=${POSTGRESS_PASSWORD}

  # Roundcube
  roundcube-fpm:
    depends_on:
      - smtp.fivestar.et
      - imap.fivestar.et
    build:
        context: ./
        dockerfile: ./docker/roundcube-fpm/Dockerfile
    image: "roundcube-fpm"
    restart: always
    environment:

      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://imap.fivestar.et
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://smtp.fivestar.et
      - ROUNDCUBEMAIL_SMTP_PORT=465

      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=50M

      #  Database
      -  ROUNDCUBEMAIL_DB_TYPE=pgsql
      -  ROUNDCUBEMAIL_DB_HOST=db
      -  ROUNDCUBEMAIL_DB_USER=${POSTGRESS_USER}
      -  ROUNDCUBEMAIL_DB_PASSWORD=${POSTGRESS_PASSWORD}
      -  ROUNDCUBEMAIL_DB_NAME=${ROUNDCUBE_DB_POSTGRESS_DB}
    volumes:
        - roundcube_code:/var/www/html/
        - roundcube_temp:/tmp/roundcube-temp

  roundcube-nginx:
    depends_on:
      - roundcube-fpm
    build:
        context: ./
        dockerfile: ./docker/roundcube-nginx/Dockerfile
    image: "roundcube-nginx"
    restart: always
    volumes:
        - roundcube_code:/var/www/html/:ro
    ports:
      - ${HOST_IP}:${ROUNDCUBE_PORT}:80
      - ${HOST_IP}:${ROUNDCUBE_PORT_TLS}:443


volumes:

  # Configs
  email_pgsql:
  postfix_socket:
  postfix-admin_templates:
  etc-dovecot:
  # Share virtual mail among postfix and dovecot
  vmail:
  
  # Shared roundcube code 
  roundcube_code:
  roundcube_logs:
  roundcube_temp:
  roundcube_config: